import { Project, CategoryData, PatientRecord } from './types';

export const CATEGORIES: CategoryData[] = [
  { name: '耳鼻喉科', count: 24, color: '#6366f1' }, // Indigo
  { name: '家醫科', count: 18, color: '#fbbf24' }, // Amber
  { name: '小兒科', count: 10, color: '#10b981' }, // Emerald
  { name: '慢性病', count: 6, color: '#a855f7' }, // Purple
];

export const PROJECTS: Project[] = [
  {
    id: '201',
    day: 1,
    category: '耳鼻喉科',
    title: '陳小明 - 急性扁桃腺炎',
    description: '主訴：喉嚨劇痛、發燒39度、吞嚥困難。檢查發現扁桃腺紅腫化膿。開立抗生素與消炎止痛藥，建議多休息。',
    tags: ['發燒', '抗生素治療'],
    date: '09:00 AM',
    link: '#',
    physician: '李華醫師'
  },
  {
    id: '202',
    day: 2,
    category: '耳鼻喉科',
    title: '林怡君 - 過敏性鼻炎',
    description: '主訴：換季打噴嚏、流鼻水、鼻塞嚴重影響睡眠。檢查鼻黏膜蒼白腫脹。開立抗組織胺與鼻噴劑。',
    tags: ['過敏', '慢性護理'],
    date: '09:15 AM',
    link: '#',
    physician: '王大明醫師'
  },
  {
    id: '203',
    day: 3,
    category: '家醫科',
    title: '王大衛 - 高血壓續藥',
    description: '慢性病連續處方箋回診。近一個月居家血壓平均 135/85 mmHg，控制尚可。維持原降血壓藥物劑量。',
    tags: ['慢箋', '三高管理'],
    date: '09:30 AM',
    link: '#',
    physician: '陳淑芬醫師'
  },
  {
    id: '204',
    day: 4,
    category: '耳鼻喉科',
    title: '張雅婷 - 突發性耳聾疑慮',
    description: '主訴：左耳突然聽不到聲音伴隨耳鳴。聽力檢查顯示左耳高頻聽力下降。安排類固醇治療並轉診大醫院做進一步檢查。',
    tags: ['急症', '聽力檢查'],
    date: '10:00 AM',
    link: '#',
    physician: '李華醫師'
  },
  {
    id: '205',
    day: 5,
    category: '小兒科',
    title: '李小寶 - 腸病毒篩檢',
    description: '幼兒園通報有腸病毒。病患手足口出現水泡，喉嚨有潰瘍。診斷為腸病毒，衛教家長注意重症前兆。',
    tags: ['傳染病', '居家隔離'],
    date: '10:30 AM',
    link: '#',
    physician: '張志豪醫師'
  },
  {
    id: '206',
    day: 6,
    category: '耳鼻喉科',
    title: '吳淑芬 - 魚刺卡喉',
    description: '主訴：晚餐吃魚後喉嚨有異物感、刺痛。經喉內視鏡檢查，於左側扁桃腺窩夾出一根細魚刺。',
    tags: ['異物取出', '處置'],
    date: '11:00 AM',
    link: '#',
    physician: '王大明醫師'
  },
  {
    id: '207',
    day: 7,
    category: '家醫科',
    title: '趙敏 - 急性腸胃炎',
    description: '主訴：上吐下瀉、腹絞痛。聽診腸音蠕動過快。給予止吐止瀉針劑治療，建議清淡飲食兩天。',
    tags: ['點滴', '急性病'],
    date: '11:15 AM',
    link: '#',
    physician: '陳淑芬醫師'
  },
  {
    id: '208',
    day: 8,
    category: '耳鼻喉科',
    title: '孫大華 - 梅尼爾氏症',
    description: '主訴：天旋地轉眩暈、噁心嘔吐。眼振檢查陽性。診斷為內耳不平衡，給予止暈藥與血液循環劑。',
    tags: ['眩暈', '長期追蹤'],
    date: '11:45 AM',
    link: '#',
    physician: '李華醫師'
  }
];

export const NAV_ITEMS = [
  { name: '診所儀表板', id: 'dashboard', icon: 'LayoutGrid' },
  { name: '病歷資料', id: 'records', icon: 'FolderOpen' },
  { name: '藥品庫存', id: 'inventory', icon: 'Lightbulb' },
];

export const PATIENT_RECORDS: PatientRecord[] = [
  {
    id: 'P2023001',
    name: '陳小明',
    gender: '男',
    dob: '1985-05-12',
    age: 38,
    idNumber: 'A123456789',
    phone: '0912-345-678',
    email: 'ming@example.com',
    address: '台北市大安區信義路三段100號',
    emergencyContact: '陳大明',
    emergencyPhone: '0911-111-222',
    firstVisitDate: '2020-01-15',
    lastVisitDate: '2023-10-25',
    mainSymptoms: '喉嚨痛、發燒',
    duration: '2天',
    pastHistory: '無重大病史',
    familyHistory: '父親有高血壓',
    allergies: 'Penicillin (盤尼西林)',
    currentMeds: '無',
    height: 175,
    weight: 70,
    bmi: 22.9,
    bp: '120/80',
    hr: 72,
    sugar: '95',
    cholesterol: '180',
    smoking: '無',
    drinking: '偶爾',
    exercise: '每週3次',
    sleepQuality: '良好',
    stressLevel: '中等',
    notes: '建議每年定期健檢'
  },
  {
    id: 'P2023002',
    name: '林怡君',
    gender: '女',
    dob: '1990-08-20',
    age: 33,
    idNumber: 'B223456789',
    phone: '0922-333-444',
    email: 'lin@example.com',
    address: '新北市板橋區文化路一段50號',
    emergencyContact: '王先生',
    emergencyPhone: '0922-555-666',
    firstVisitDate: '2021-03-10',
    lastVisitDate: '2023-10-26',
    mainSymptoms: '鼻塞、流鼻水',
    duration: '1週',
    pastHistory: '過敏性鼻炎',
    familyHistory: '母親有糖尿病',
    allergies: '無',
    currentMeds: '抗組織胺',
    height: 160,
    weight: 52,
    bmi: 20.3,
    bp: '110/70',
    hr: 68,
    sugar: '90',
    cholesterol: '160',
    smoking: '無',
    drinking: '無',
    exercise: '無',
    sleepQuality: '差 (因鼻塞)',
    stressLevel: '高',
    notes: '換季時症狀加劇'
  },
  {
    id: 'P2023003',
    name: '王大衛',
    gender: '男',
    dob: '1965-11-30',
    age: 58,
    idNumber: 'C123456789',
    phone: '0933-444-555',
    email: 'david@example.com',
    address: '台北市松山區民生東路五段',
    emergencyContact: '王太太',
    emergencyPhone: '0933-666-777',
    firstVisitDate: '2019-06-01',
    lastVisitDate: '2023-10-27',
    mainSymptoms: '定期回診領藥',
    duration: '-',
    pastHistory: '高血壓、高血脂',
    familyHistory: '父母皆有高血壓',
    allergies: 'Aspirin',
    currentMeds: '降血壓藥 (Amlodipine)',
    height: 170,
    weight: 85,
    bmi: 29.4,
    bp: '135/85',
    hr: 75,
    sugar: '110',
    cholesterol: '220',
    smoking: '已戒菸',
    drinking: '經常',
    exercise: '偶爾',
    sleepQuality: '普通',
    stressLevel: '低',
    notes: '需控制飲食，減少鹽分攝取'
  },
  {
    id: 'P2023004',
    name: '張雅婷',
    gender: '女',
    dob: '1978-02-14',
    age: 45,
    idNumber: 'D223456789',
    phone: '0944-555-666',
    email: 'chang@example.com',
    address: '台中市西區台灣大道二段',
    emergencyContact: '陳先生',
    emergencyPhone: '0944-777-888',
    firstVisitDate: '2022-12-05',
    lastVisitDate: '2023-10-28',
    mainSymptoms: '突發性聽力下降',
    duration: '3小時',
    pastHistory: '無',
    familyHistory: '無',
    allergies: '無',
    currentMeds: '無',
    height: 165,
    weight: 58,
    bmi: 21.3,
    bp: '118/76',
    hr: 70,
    sugar: '92',
    cholesterol: '170',
    smoking: '無',
    drinking: '無',
    exercise: '每週2次',
    sleepQuality: '良好',
    stressLevel: '高',
    notes: '已安排轉診大醫院進行MRI檢查'
  },
  {
    id: 'P2023005',
    name: '孫大華',
    gender: '男',
    dob: '1980-09-09',
    age: 43,
    idNumber: 'E123456789',
    phone: '0955-666-777',
    email: 'sun@example.com',
    address: '台北市文山區指南路',
    emergencyContact: '林小姐',
    emergencyPhone: '0955-888-999',
    firstVisitDate: '2023-01-20',
    lastVisitDate: '2023-10-30',
    mainSymptoms: '眩暈、噁心',
    duration: '反覆發作',
    pastHistory: '梅尼爾氏症',
    familyHistory: '不明',
    allergies: '桃子毛 (輕微)',
    currentMeds: '止暈藥',
    height: 172,
    weight: 65,
    bmi: 22.0,
    bp: '125/82',
    hr: 80,
    sugar: '98',
    cholesterol: '190',
    smoking: '無',
    drinking: '無',
    exercise: '每天',
    sleepQuality: '差 (受眩暈影響)',
    stressLevel: '高',
    notes: '建議避免劇烈頭部運動'
  }
];